// shared/constants.js — Shared constants across all modules
// DEV3: Read only. Do NOT edit this file.

const PROCESS_SCAN_INTERVAL_MS = 30000; // 30 seconds

const EVENTS = {
  SESSION_START: 'session:start',
  SESSION_END: 'session:end',
  PROCESS: 'signal:process',
  DETECTION: 'signal:detection',
  GAZE: 'signal:gaze',
};

module.exports = {
  PROCESS_SCAN_INTERVAL_MS,
  EVENTS,
};
