// shared/types.js — Shared type definitions / payload shapes
// DEV3: Read only. Do NOT edit this file.

/**
 * ProcessSignalPayload — Shape of the object emitted on EVENTS.PROCESS
 *
 * {
 *   flagged: boolean,         // true if a suspicious process was detected
 *   processName: string,      // name of the flagged process (empty string if none)
 *   category: string,         // 'ai_overlay' | 'screen_reader' | 'clipboard_ai' | 'unknown'
 *   ts: number                // Unix timestamp (Date.now())
 * }
 */

module.exports = {};
